### ISSUE TITLE
Error when using environment variables

### ISSUE THREAD

**Issue by htrgouvea** [insidersec/insider-action#1]
Hi guys,

I'm trying to use this Action in my project (https://github.com/GouveaHeitor/gouveaheitor.github.io/blob/master/.github/workflows/insider_scan.yml) and I have a small problem...

As I am passing an environment variable called $ GITHUB_WORKSPACE, it seems that the Insider binary is not finding it:

https://github.com/GouveaHeitor/gouveaheitor.github.io/runs/842012665?check_suite_focus=true

Reference: https://docs.github.com/pt/actions/configuring-and-managing-workflows/using-environment-variables

Thx!

**Comment by mattheusv** [comment]
Hi @GouveaHeitor, thanks for the issue. We did an update to use the `target` entry always as a relative path to $ GITHUB_WORKSPACE; therefore, if you want to use $ GITHUB_WORKSPACE, you can fill in `target` with ". " or leave it blank ([since the target's default value is "."](https://github.com/marketplace/actions/insider-action#inputs)). You can also read the [docs](https://github.com/marketplace/actions/insider-action) for more information about.

Can you try again if this new release?

**Comment by htrgouvea** [comment]
Hi @msAlcantara,

I just saw the latest updates here and on the insider and it looks like everything works perfectly now!

https://github.com/GouveaHeitor/gouveaheitor.github.io/runs/850942917?check_suite_focus=true

Thx!
